#!/usr/bin/env python3
"""
Interactive plot of tsunami simulation output.
Reads tsunami_output.txt (generated by the Fortran tsunami program)
and displays the wave height h(x) at each time step with a slider
to scrub through time.
"""

import re
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider
import os

# --- Configuration ---
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_FILE = os.path.join(SCRIPT_DIR, "tsunami_output.txt")
NX = 100          # number of grid points (must match tsunami.f90)

# --- Parse the output file ---
def parse_output(filepath: str, nx: int) -> tuple[list[int], list[list[float]]]:
    """Parse Fortran `print *, n, h` output into time steps and grid data.

    Each line in the file starts with the time-step index (integer), followed
    by `nx` floating-point values.  Some values use Fortran E-notation, e.g.
    `7.44451284E-02`, which Python's `float()` handles natively.
    """
    times: list[int] = []
    data: list[list[float]] = []

    # Regex to split on whitespace, tolerant of Fortran E-notation
    tokenizer = re.compile(r"\S+")

    with open(filepath) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            tokens = tokenizer.findall(line)
            if len(tokens) < 1 + nx:
                continue  # skip incomplete / malformed lines
            try:
                t = int(tokens[0])
            except ValueError:
                continue
            try:
                values = [float(tok) for tok in tokens[1:1 + nx]]
            except ValueError:
                continue
            times.append(t)
            data.append(values)

    return times, data


# --- Interactive plot ---
def main():
    times, data = parse_output(DATA_FILE, NX)

    if not times:
        print(f"ERROR: No valid data found in {DATA_FILE}")
        return

    print(f"Loaded {len(times)} time steps × {NX} grid points from {DATA_FILE}")

    x = list(range(1, NX + 1))  # grid index 1..nx

    # Set up the figure
    fig, ax = plt.subplots(figsize=(12, 5))
    plt.subplots_adjust(bottom=0.20)  # make room for slider

    # Initial plot (first time step)
    line, = ax.plot(x, data[0], lw=1.5)
    ax.set_xlim(1, NX)
    ax.set_ylim(-0.05, 1.05)
    ax.set_xlabel("Grid point i")
    ax.set_ylabel("Wave height h(i)")
    ax.grid(True, alpha=0.3)
    title = ax.set_title(f"Tsunami — time step {times[0]}")

    # Slider axis
    slider_ax = plt.axes([0.15, 0.05, 0.70, 0.04])
    slider = Slider(
        ax=slider_ax,
        label="Time step",
        valmin=times[0],
        valmax=times[-1],
        valinit=times[0],
        valstep=times,       # snap to integer time steps
    )

    def update(val: float):
        """Called when the slider moves."""
        idx = times.index(int(val))
        line.set_ydata(data[idx])
        title.set_text(f"Tsunami — time step {times[idx]}")
        fig.canvas.draw_idle()

    slider.on_changed(update)

    # Keyboard navigation: left/right arrows
    def on_key(event):
        current_idx = times.index(int(slider.val))
        if event.key == "right" and current_idx < len(times) - 1:
            slider.set_val(times[current_idx + 1])
        elif event.key == "left" and current_idx > 0:
            slider.set_val(times[current_idx - 1])

    fig.canvas.mpl_connect("key_press_event", on_key)

    plt.show()


if __name__ == "__main__":
    main()
